from dataclasses import dataclass, field
from src.domain.entity.stats.stats import (
    Health,
    HandSkill,
    ActionPoint,
    Bravery,
    Endurance,
    Initiative,
    MeleeDefense,
    ShootingProtection,
    Damage,
    Visibility,
    Moral,
    ShootingSkill,
    DamageArmor,
    HeadHitChance,
    HeadArmor,
    BodyArmor,
)
from src.domain.value_object.perk import PerkMultiplier
from typing import Self

@dataclass
class GroupStat:
    _level: int = field(default=0, init=False)

    _health: Health = field(default_factory=Health, init=False)
    _action_point: ActionPoint = field(default_factory=ActionPoint, init=False)
    _bravery: Bravery = field(default_factory=Bravery, init=False)
    _endurance: Endurance = field(default_factory=Endurance, init=False)
    _initiative: Initiative = field(default_factory=Initiative, init=False)
    _melee_defense: MeleeDefense = field(default_factory=MeleeDefense, init=False)
    _shooting_protection: ShootingProtection = field(
        default_factory=ShootingProtection, init=False
    )
    _damage: Damage = field(default_factory=Damage, init=False)
    _visibility: Visibility = field(default_factory=Visibility, init=False)
    _moral: Moral = field(default_factory=Moral, init=False)
    _hand_skill: HandSkill = field(default_factory=HandSkill, init=False)
    _shooting_skill: ShootingSkill = field(default_factory=ShootingSkill, init=False)
    _damage_armor: DamageArmor = field(default_factory=DamageArmor, init=False)
    _head_hit_chance: HeadHitChance = field(default_factory=HeadHitChance, init=False)
    _head_armor: HeadArmor = field(default_factory=HeadArmor, init=False)
    _body_armor: BodyArmor = field(default_factory=BodyArmor, init=False)

    @property
    def level(self) -> int: ...
    @property
    def health(self) -> Health: ...
    @property
    def action_point(self) -> ActionPoint: ...
    @property
    def bravery(self) -> Bravery: ...
    @property
    def endurance(self) -> Endurance: ...
    @property
    def initiative(self) -> Initiative: ...
    @property
    def melee_defense(self) -> MeleeDefense: ...
    @property
    def shooting_protection(self) -> ShootingProtection: ...
    @property
    def damage(self) -> Damage: ...
    @property
    def visibility(self) -> Visibility: ...
    @property
    def moral(self) -> Moral: ...
    @property
    def hand_skill(self) -> HandSkill: ...
    @property
    def shooting_skill(self) -> ShootingSkill: ...
    @property
    def damage_armor(self) -> DamageArmor: ...
    @property
    def head_hit_chance(self) -> HeadHitChance: ...
    @property
    def head_armor(self) -> HeadArmor: ...
    @property
    def body_armor(self) -> BodyArmor: ...

    def get_copy(self) -> "GroupStat": ...
    def get_copy_without_multiplier(self) -> "GroupStat": ...
    def level_up(self) -> None: ...
    def append_multipliers(self, multiplier: PerkMultiplier): ...
    def remove_multipliers(self, multiplier: PerkMultiplier): ...

    def with_health(self, current: int, maximum: int) -> Self: ...
    def with_action_point(self, current: int, maximum: int) -> Self: ...
    def with_bravery(self, current: int, maximum: int) -> Self: ...
    def with_endurance(self, current: int, maximum: int) -> Self: ...
    def with_initiative(self, current: int, maximum: int) -> Self: ...
    def with_melee_defense(self, current: int, maximum: int) -> Self: ...
    def with_shooting_protection(self, current: int, maximum: int) -> Self: ...
    def with_damage(self, current: tuple[int, int], maximum: int) -> Self: ...
    def with_visibility(self, current: int, maximum: int) -> Self: ...
    def with_moral(self, current: int, maximum: int) -> Self: ...
    def with_hand_skill(self, current: int, maximum: int) -> Self: ...
    def with_shooting_skill(self, current: int, maximum: int) -> Self: ...
    def with_damage_armor(self, current: int, maximum: int) -> Self: ...
    def with_head_hit_chance(self, current: int, maximum: int) -> Self: ...
    def with_head_armor(self, current: int, maximum: int) -> Self: ...
    def with_body_armor(self, current: int, maximum: int) -> Self: ...
