from collections import deque
from src.domain.entity.stats import GroupStat, StatEnum, MultiplierObject, BaseStat

class StatsService:
    def __init__(self) -> None: 
        self.builder_stats: 'StatsService.GenerateCustomStat' = StatsService.GenerateCustomStat()
        ...

    @property
    def current_stats(self) -> GroupStat: ...

    def generate_default_stats(self) -> GroupStat: ...

    def generate_random_stats(self, level: int = 0) -> GroupStat: ...

    def _get_stat(self, stat: StatEnum) -> BaseStat: ...

    def append_multipliers(self, stat: StatEnum, multiplier: MultiplierObject) -> None: ...

    def remove_multipliers(self, stat: StatEnum, multiplier: MultiplierObject) -> None: ...

    def level_up(self) -> None: ...

    class GenerateCustomStat:
        def __init__(self) -> None: 
            self.stats_result: GroupStat = GroupStat()
            self.history_stats: deque[GroupStat] = deque(maxlen=100)
            ...

        def health(self, *, current: int, maximum: int) -> \
                'StatsService.GenerateCustomStat': ...

        def hand_skill(self, *, current: int, maximum: int) -> \
                'StatsService.GenerateCustomStat': ...